[package]
name = "kawa"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>", "ParadoxSpiral <ParadoxSpiral@riseup.net>"]

[dependencies]
shout = "0.1.6"
libc = "0.2"
toml = "0.3"
rustful = "0.9.0"
hyper = "0.9"
redis = "0.5.3"
slog = "1.3"
slog-term = "1.3.3"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"

[dependencies.ffmpeg]
version = "0.2.0-alpha.11"
git = "https://github.com/luminarys/rust-ffmpeg"

[dependencies.ring-buffer]
version = "0.1.0"
git = "https://github.com/luminarys/ring-buffer"
