[package]
name = "kawa"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]

[dependencies]
shout = "0.1.5"
libc = "0.2"
hyper = "0.9"
toml = "0.2.0"
rustful = "0.9.0"
rustc-serialize = "0.3"

[dependencies.ffmpeg]
version = "0.2.0-alpha.5"
git = "https://github.com/luminarys/rust-ffmpeg"
