[api]
port=4040

[queue]
random_song_api="http://localhost:8012/api/random"
np="http://localhost:8012/api/np"
fallback="/tmp/in.flac"

[radio]
port=8001

[[streams]]
mount="stream128.mp3"
bitrate=128
container="mp3"

[[streams]]
mount="stream192.mp3"
bitrate=192
container="mp3"

[[streams]]
mount="stream128.opus"
container="ogg"
codec="opus"
bitrate=128

[[streams]]
mount="stream192.opus"
container="ogg"
codec="opus"
bitrate=192

[[streams]]
mount="stream256.opus"
container="ogg"
codec="opus"
bitrate=256

[[streams]]
mount="stream.flac"
container="ogg"
codec="flac"
