[package]
name = "kaeru"
version = "0.1.0"
authors = ["Luminarys <postmaster@gensok.io>"]

[dependencies.ffmpeg-sys]
version = "3.3.2"
git = "https://github.com/meh/rust-ffmpeg-sys.git"
default-features = false
features = ["avcodec", "avfilter", "avformat"]
